/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPStackMessageQueue */

#ifndef _Included_com_openpeer_javaapi_OPStackMessageQueue
#define _Included_com_openpeer_javaapi_OPStackMessageQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPStackMessageQueue
 * Method:    singleton
 * Signature: ()Lcom/openpeer/javaapi/OPStackMessageQueue;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPStackMessageQueue_singleton
  (JNIEnv *, jclass);

/*
 * Class:     com_openpeer_javaapi_OPStackMessageQueue
 * Method:    interceptProcessing
 * Signature: (Lcom/openpeer/javaapi/OPStackMessageQueueDelegate;)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPStackMessageQueue_interceptProcessing
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_openpeer_javaapi_OPStackMessageQueue
 * Method:    notifyProcessMessageFromCustomThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPStackMessageQueue_notifyProcessMessageFromCustomThread
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
