/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPSettings */

#ifndef _Included_com_openpeer_javaapi_OPSettings
#define _Included_com_openpeer_javaapi_OPSettings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPSettings
 * Method:    setup
 * Signature: (Lcom/openpeer/javaapi/OPSettingsDelegate;)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPSettings_setup
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_openpeer_javaapi_OPSettings
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPSettings_setString
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_openpeer_javaapi_OPSettings
 * Method:    setInt
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPSettings_setInt
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_openpeer_javaapi_OPSettings
 * Method:    setUInt
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPSettings_setUInt
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_openpeer_javaapi_OPSettings
 * Method:    setBool
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPSettings_setBool
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_openpeer_javaapi_OPSettings
 * Method:    setFloat
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPSettings_setFloat
  (JNIEnv *, jclass, jstring, jfloat);

/*
 * Class:     com_openpeer_javaapi_OPSettings
 * Method:    setDouble
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPSettings_setDouble
  (JNIEnv *, jclass, jstring, jdouble);

/*
 * Class:     com_openpeer_javaapi_OPSettings
 * Method:    clear
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPSettings_clear
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_openpeer_javaapi_OPSettings
 * Method:    apply
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_openpeer_javaapi_OPSettings_apply
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_openpeer_javaapi_OPSettings
 * Method:    applyDefaults
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPSettings_applyDefaults
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
