/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPCallSystemMessage */

#ifndef _Included_com_openpeer_javaapi_OPCallSystemMessage
#define _Included_com_openpeer_javaapi_OPCallSystemMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPCallSystemMessage
 * Method:    toString
 * Signature: (Lcom/openpeer/javaapi/CallSystemMessageTypes;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_openpeer_javaapi_OPCallSystemMessage_toString
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_openpeer_javaapi_OPCallSystemMessage
 * Method:    toCallSystemMessageType
 * Signature: (Ljava/lang/String;)Lcom/openpeer/javaapi/CallSystemMessageTypes;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPCallSystemMessage_toCallSystemMessageType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_openpeer_javaapi_OPCallSystemMessage
 * Method:    create
 * Signature: (Lcom/openpeer/javaapi/CallSystemMessageTypes;Lcom/openpeer/javaapi/OPContact;I)Lcom/openpeer/javaapi/OPCallSystemMessage;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPCallSystemMessage_create
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_openpeer_javaapi_OPCallSystemMessage
 * Method:    extract
 * Signature: (Lcom/openpeer/javaapi/OPElement;Lcom/openpeer/javaapi/OPAccount;)Lcom/openpeer/javaapi/OPCallSystemMessage;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPCallSystemMessage_extract
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_openpeer_javaapi_OPCallSystemMessage
 * Method:    insert
 * Signature: (Lcom/openpeer/javaapi/OPElement;)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPCallSystemMessage_insert
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_openpeer_javaapi_OPCallSystemMessage
 * Method:    hasData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_openpeer_javaapi_OPCallSystemMessage_hasData
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPCallSystemMessage
 * Method:    toDebug
 * Signature: ()Lcom/openpeer/javaapi/OPElement;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPCallSystemMessage_toDebug
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPCallSystemMessage
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPCallSystemMessage_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
