/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPSystemMessage */

#ifndef _Included_com_openpeer_javaapi_OPSystemMessage
#define _Included_com_openpeer_javaapi_OPSystemMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPSystemMessage
 * Method:    createEmptySystemMessage
 * Signature: ()Lcom/openpeer/javaapi/OPElement;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPSystemMessage_createEmptySystemMessage
  (JNIEnv *, jclass);

/*
 * Class:     com_openpeer_javaapi_OPSystemMessage
 * Method:    getMessageType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_openpeer_javaapi_OPSystemMessage_getMessageType
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
