/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPConversationThreadType */

#ifndef _Included_com_openpeer_javaapi_OPConversationThreadType
#define _Included_com_openpeer_javaapi_OPConversationThreadType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPConversationThreadType
 * Method:    toString
 * Signature: (Lcom/openpeer/javaapi/ConversationThreadTypes;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_openpeer_javaapi_OPConversationThreadType_toString
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_openpeer_javaapi_OPConversationThreadType
 * Method:    toConversationThreadType
 * Signature: (Ljava/lang/String;)Lcom/openpeer/javaapi/ConversationThreadTypes;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPConversationThreadType_toConversationThreadType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_openpeer_javaapi_OPConversationThreadType
 * Method:    extract
 * Signature: (Lcom/openpeer/javaapi/OPElement;)Lcom/openpeer/javaapi/OPConversationThreadType;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPConversationThreadType_extract
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_openpeer_javaapi_OPConversationThreadType
 * Method:    insert
 * Signature: (Lcom/openpeer/javaapi/OPElement;)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPConversationThreadType_insert
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_openpeer_javaapi_OPConversationThreadType
 * Method:    hasData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_openpeer_javaapi_OPConversationThreadType_hasData
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPConversationThreadType
 * Method:    toDebug
 * Signature: ()Lcom/openpeer/javaapi/OPElement;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPConversationThreadType_toDebug
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPConversationThreadType
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPConversationThreadType_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
