#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("OpenPeerSampleAppCSharp.Resource", IsApplication=true)]

namespace OpenPeerSampleAppCSharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PullToRefresharp.Resource.Attribute.contentViewId = global::OpenPeerSampleAppCSharp.Resource.Attribute.contentViewId;
			global::PullToRefresharp.Resource.Attribute.fastScrollThumbWidth = global::OpenPeerSampleAppCSharp.Resource.Attribute.fastScrollThumbWidth;
			global::PullToRefresharp.Resource.Attribute.headerIconDrawable = global::OpenPeerSampleAppCSharp.Resource.Attribute.headerIconDrawable;
			global::PullToRefresharp.Resource.Attribute.headerId = global::OpenPeerSampleAppCSharp.Resource.Attribute.headerId;
			global::PullToRefresharp.Resource.Attribute.headerTextColor = global::OpenPeerSampleAppCSharp.Resource.Attribute.headerTextColor;
			global::PullToRefresharp.Resource.Attribute.ptrHeaderBackground = global::OpenPeerSampleAppCSharp.Resource.Attribute.ptrHeaderBackground;
			global::PullToRefresharp.Resource.Attribute.pullDownProgressIndicatorId = global::OpenPeerSampleAppCSharp.Resource.Attribute.pullDownProgressIndicatorId;
			global::PullToRefresharp.Resource.Attribute.pullDownTension = global::OpenPeerSampleAppCSharp.Resource.Attribute.pullDownTension;
			global::PullToRefresharp.Resource.Attribute.pullEnabled = global::OpenPeerSampleAppCSharp.Resource.Attribute.pullEnabled;
			global::PullToRefresharp.Resource.Attribute.pullToRefreshText = global::OpenPeerSampleAppCSharp.Resource.Attribute.pullToRefreshText;
			global::PullToRefresharp.Resource.Attribute.refreshingText = global::OpenPeerSampleAppCSharp.Resource.Attribute.refreshingText;
			global::PullToRefresharp.Resource.Attribute.releaseToRefreshText = global::OpenPeerSampleAppCSharp.Resource.Attribute.releaseToRefreshText;
			global::PullToRefresharp.Resource.Attribute.snapbackDuration = global::OpenPeerSampleAppCSharp.Resource.Attribute.snapbackDuration;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_end = global::OpenPeerSampleAppCSharp.Resource.Color.ptrsharp_sb_gradient_end;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_start = global::OpenPeerSampleAppCSharp.Resource.Color.ptrsharp_sb_gradient_start;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_header_text = global::OpenPeerSampleAppCSharp.Resource.Color.ptrsharp_sb_header_text;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_header_text_shadow = global::OpenPeerSampleAppCSharp.Resource.Color.ptrsharp_sb_header_text_shadow;
			global::PullToRefresharp.Resource.Dimension.fastscroll_thumb_width = global::OpenPeerSampleAppCSharp.Resource.Dimension.fastscroll_thumb_width;
			global::PullToRefresharp.Resource.Drawable.progress_medium_holo = global::OpenPeerSampleAppCSharp.Resource.Drawable.progress_medium_holo;
			global::PullToRefresharp.Resource.Drawable.ptrsharp_serious_business_gradient = global::OpenPeerSampleAppCSharp.Resource.Drawable.ptrsharp_serious_business_gradient;
			global::PullToRefresharp.Resource.Drawable.serious_business_arrow = global::OpenPeerSampleAppCSharp.Resource.Drawable.serious_business_arrow;
			global::PullToRefresharp.Resource.Drawable.serious_business_arrow2 = global::OpenPeerSampleAppCSharp.Resource.Drawable.serious_business_arrow2;
			global::PullToRefresharp.Resource.Drawable.spinner_20_inner_holo = global::OpenPeerSampleAppCSharp.Resource.Drawable.spinner_20_inner_holo;
			global::PullToRefresharp.Resource.Drawable.spinner_20_outer_holo = global::OpenPeerSampleAppCSharp.Resource.Drawable.spinner_20_outer_holo;
			global::PullToRefresharp.Resource.Id.header = global::OpenPeerSampleAppCSharp.Resource.Id.header;
			global::PullToRefresharp.Resource.Id.header_container = global::OpenPeerSampleAppCSharp.Resource.Id.header_container;
			global::PullToRefresharp.Resource.Id.icon = global::OpenPeerSampleAppCSharp.Resource.Id.icon;
			global::PullToRefresharp.Resource.Id.pullDownProgressIndicator = global::OpenPeerSampleAppCSharp.Resource.Id.pullDownProgressIndicator;
			global::PullToRefresharp.Resource.Id.text = global::OpenPeerSampleAppCSharp.Resource.Id.text;
			global::PullToRefresharp.Resource.Layout.ptrsharp_header = global::OpenPeerSampleAppCSharp.Resource.Layout.ptrsharp_header;
			global::PullToRefresharp.Resource.String.library_name = global::OpenPeerSampleAppCSharp.Resource.String.library_name;
			global::PullToRefresharp.Resource.String.ptrsharp_pull_to_refresh = global::OpenPeerSampleAppCSharp.Resource.String.ptrsharp_pull_to_refresh;
			global::PullToRefresharp.Resource.String.ptrsharp_refreshing = global::OpenPeerSampleAppCSharp.Resource.String.ptrsharp_refreshing;
			global::PullToRefresharp.Resource.String.ptrsharp_release_to_refresh = global::OpenPeerSampleAppCSharp.Resource.String.ptrsharp_release_to_refresh;
			global::PullToRefresharp.Resource.Style.HoloProgressMedium = global::OpenPeerSampleAppCSharp.Resource.Style.HoloProgressMedium;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_contentViewId = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_contentViewId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_fastScrollThumbWidth = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_fastScrollThumbWidth;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerId = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_headerId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerTextColor = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_headerTextColor;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownTension = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_pullDownTension;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullEnabled = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_pullEnabled;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_refreshingText = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_refreshingText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration = global::OpenPeerSampleAppCSharp.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int log_levels_array = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int log_subsystem_array = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int log_subsystem_friend_names_array = 2131230721;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int contentViewId = 2130771969;
			
			// aapt resource value: 0x7f01000c
			public const int fastScrollThumbWidth = 2130771980;
			
			// aapt resource value: 0x7f01000a
			public const int headerIconDrawable = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int headerId = 2130771968;
			
			// aapt resource value: 0x7f010009
			public const int headerTextColor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int ptrHeaderBackground = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int pullDownProgressIndicatorId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int pullDownTension = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int pullEnabled = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int pullToRefreshText = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int refreshingText = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int releaseToRefreshText = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int snapbackDuration = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int ptrsharp_sb_gradient_end = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int ptrsharp_sb_gradient_start = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ptrsharp_sb_header_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ptrsharp_sb_header_text_shadow = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int fastscroll_thumb_width = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int chat = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int chat_alt = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int chat_bubble_left = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int chat_bubble_left_source = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int chat_bubble_right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int chat_bubble_right_source = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int progress_medium_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ptrsharp_serious_business_gradient = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int serious_business_arrow = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int serious_business_arrow2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int spinner_20_inner_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int spinner_20_outer_holo = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0005
			public const int avatarImageView = 2131361797;
			
			// aapt resource value: 0x7f0a0011
			public const int badgeAnchorTextView = 2131361809;
			
			// aapt resource value: 0x7f0a000f
			public const int badgeRelativeLayout = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int badgeSpacerRelativeLayout = 2131361808;
			
			// aapt resource value: 0x7f0a0007
			public const int bubbleImageView = 2131361799;
			
			// aapt resource value: 0x7f0a0006
			public const int bubbleTextRelativeLayout = 2131361798;
			
			// aapt resource value: 0x7f0a0008
			public const int bubbleTextView = 2131361800;
			
			// aapt resource value: 0x7f0a000e
			public const int chatIcon = 2131361806;
			
			// aapt resource value: 0x7f0a0009
			public const int contactItemLinearLayout = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int contactItemRelativeLayout = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int detailsRelativeLayout = 2131361803;
			
			// aapt resource value: 0x7f0a0002
			public const int editText = 2131361794;
			
			// aapt resource value: 0x7f0a0017
			public const int header = 2131361815;
			
			// aapt resource value: 0x7f0a0016
			public const int header_container = 2131361814;
			
			// aapt resource value: 0x7f0a0019
			public const int icon = 2131361817;
			
			// aapt resource value: 0x7f0a001d
			public const int labelTextView = 2131361821;
			
			// aapt resource value: 0x7f0a0015
			public const int linearLayout = 2131361813;
			
			// aapt resource value: 0x7f0a0013
			public const int loginWebView = 2131361811;
			
			// aapt resource value: 0x7f0a0023
			public const int logoutMenuItem = 2131361827;
			
			// aapt resource value: 0x7f0a0003
			public const int nameTextView = 2131361795;
			
			// aapt resource value: 0x7f0a0012
			public const int ptr_wrapper = 2131361810;
			
			// aapt resource value: 0x7f0a0018
			public const int pullDownProgressIndicator = 2131361816;
			
			// aapt resource value: 0x7f0a001c
			public const int relativeLayout = 2131361820;
			
			// aapt resource value: 0x7f0a0001
			public const int sendButton = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int sendRelativeLayout = 2131361792;
			
			// aapt resource value: 0x7f0a0022
			public const int settingsMenuItem = 2131361826;
			
			// aapt resource value: 0x7f0a001b
			public const int settingsSpinnerListItem = 2131361819;
			
			// aapt resource value: 0x7f0a001f
			public const int settingsTextEditListItem = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int settingsToggleListItem = 2131361824;
			
			// aapt resource value: 0x7f0a0014
			public const int tabHost = 2131361812;
			
			// aapt resource value: 0x7f0a001a
			public const int text = 2131361818;
			
			// aapt resource value: 0x7f0a000c
			public const int textAreaLinearLayout = 2131361804;
			
			// aapt resource value: 0x7f0a0004
			public const int timeTextView = 2131361796;
			
			// aapt resource value: 0x7f0a0021
			public const int toggleButton = 2131361825;
			
			// aapt resource value: 0x7f0a000d
			public const int usernameTextView = 2131361805;
			
			// aapt resource value: 0x7f0a001e
			public const int valueSpinner = 2131361822;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Chat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChatLeftSideHeaderListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChatLeftSideListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ChatMarginHeaderListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ChatRightSideHeaderListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ChatRightSideListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ContactListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Contacts = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ContactsWithPull = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Login = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ptrsharp_header = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Settings = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SettingsSpinnerListItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SettingsTextEditListItem = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SettingsToggleListItem = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Splash = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int main_menu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060005
			public const int app_name = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int hello = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int outgoing_telnet_logger = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int outgoing_telnet_logger_server_prompt = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int ptrsharp_pull_to_refresh = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int ptrsharp_refreshing = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ptrsharp_release_to_refresh = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int standard_out_logger = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int telnet_logger = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int telnet_logger_port_prompt = 2131099658;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int HoloProgressMedium = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefresharpWrapper = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public const int PullToRefresharpWrapper_contentViewId = 1;
			
			// aapt resource value: 12
			public const int PullToRefresharpWrapper_fastScrollThumbWidth = 12;
			
			// aapt resource value: 10
			public const int PullToRefresharpWrapper_headerIconDrawable = 10;
			
			// aapt resource value: 0
			public const int PullToRefresharpWrapper_headerId = 0;
			
			// aapt resource value: 9
			public const int PullToRefresharpWrapper_headerTextColor = 9;
			
			// aapt resource value: 8
			public const int PullToRefresharpWrapper_ptrHeaderBackground = 8;
			
			// aapt resource value: 2
			public const int PullToRefresharpWrapper_pullDownProgressIndicatorId = 2;
			
			// aapt resource value: 4
			public const int PullToRefresharpWrapper_pullDownTension = 4;
			
			// aapt resource value: 11
			public const int PullToRefresharpWrapper_pullEnabled = 11;
			
			// aapt resource value: 5
			public const int PullToRefresharpWrapper_pullToRefreshText = 5;
			
			// aapt resource value: 7
			public const int PullToRefresharpWrapper_refreshingText = 7;
			
			// aapt resource value: 6
			public const int PullToRefresharpWrapper_releaseToRefreshText = 6;
			
			// aapt resource value: 3
			public const int PullToRefresharpWrapper_snapbackDuration = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
