package com.openpeer.sdk.app;

public enum OPCoreLogModules {
	MODULE_APPLICATION,
    MODEULE_SDK,
    MODULE_MEDIA,
    MODULE_WEBRTC,
    MODULE_CORE,
    MODULE_STACK_MESSAGE,
    MODULE_STACK,
    MODULE_SERVICES,
    MODULE_SERVICES_WIRE,
    MODULE_SERVICES_ICE,
    MODULE_SERVICES_TURN,
    MODULE_SERVICES_RUDP,
    MODULE_SERVICES_HTTP,
    MODULE_SERVICES_MLS,
    MODULE_SERVICES_TCP,
    MODULE_SERVICES_TRANSPORT,
    MODULE_ZSLIB,
    MODULE_ZSLIB_SOCKET,
    MODULE_JAVASCRIPT,
    
    TOTAL_MODULES
}
