#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("HopSampleApp.Resource", IsApplication=true)]

namespace HopSampleApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PullToRefresharp.Resource.Attribute.contentViewId = global::HopSampleApp.Resource.Attribute.contentViewId;
			global::PullToRefresharp.Resource.Attribute.fastScrollThumbWidth = global::HopSampleApp.Resource.Attribute.fastScrollThumbWidth;
			global::PullToRefresharp.Resource.Attribute.headerIconDrawable = global::HopSampleApp.Resource.Attribute.headerIconDrawable;
			global::PullToRefresharp.Resource.Attribute.headerId = global::HopSampleApp.Resource.Attribute.headerId;
			global::PullToRefresharp.Resource.Attribute.headerTextColor = global::HopSampleApp.Resource.Attribute.headerTextColor;
			global::PullToRefresharp.Resource.Attribute.ptrHeaderBackground = global::HopSampleApp.Resource.Attribute.ptrHeaderBackground;
			global::PullToRefresharp.Resource.Attribute.pullDownProgressIndicatorId = global::HopSampleApp.Resource.Attribute.pullDownProgressIndicatorId;
			global::PullToRefresharp.Resource.Attribute.pullDownTension = global::HopSampleApp.Resource.Attribute.pullDownTension;
			global::PullToRefresharp.Resource.Attribute.pullEnabled = global::HopSampleApp.Resource.Attribute.pullEnabled;
			global::PullToRefresharp.Resource.Attribute.pullToRefreshText = global::HopSampleApp.Resource.Attribute.pullToRefreshText;
			global::PullToRefresharp.Resource.Attribute.refreshingText = global::HopSampleApp.Resource.Attribute.refreshingText;
			global::PullToRefresharp.Resource.Attribute.releaseToRefreshText = global::HopSampleApp.Resource.Attribute.releaseToRefreshText;
			global::PullToRefresharp.Resource.Attribute.snapbackDuration = global::HopSampleApp.Resource.Attribute.snapbackDuration;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_end = global::HopSampleApp.Resource.Color.ptrsharp_sb_gradient_end;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_start = global::HopSampleApp.Resource.Color.ptrsharp_sb_gradient_start;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_header_text = global::HopSampleApp.Resource.Color.ptrsharp_sb_header_text;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_header_text_shadow = global::HopSampleApp.Resource.Color.ptrsharp_sb_header_text_shadow;
			global::PullToRefresharp.Resource.Dimension.fastscroll_thumb_width = global::HopSampleApp.Resource.Dimension.fastscroll_thumb_width;
			global::PullToRefresharp.Resource.Drawable.progress_medium_holo = global::HopSampleApp.Resource.Drawable.progress_medium_holo;
			global::PullToRefresharp.Resource.Drawable.ptrsharp_serious_business_gradient = global::HopSampleApp.Resource.Drawable.ptrsharp_serious_business_gradient;
			global::PullToRefresharp.Resource.Drawable.serious_business_arrow = global::HopSampleApp.Resource.Drawable.serious_business_arrow;
			global::PullToRefresharp.Resource.Drawable.serious_business_arrow2 = global::HopSampleApp.Resource.Drawable.serious_business_arrow2;
			global::PullToRefresharp.Resource.Drawable.spinner_20_inner_holo = global::HopSampleApp.Resource.Drawable.spinner_20_inner_holo;
			global::PullToRefresharp.Resource.Drawable.spinner_20_outer_holo = global::HopSampleApp.Resource.Drawable.spinner_20_outer_holo;
			global::PullToRefresharp.Resource.Id.header = global::HopSampleApp.Resource.Id.header;
			global::PullToRefresharp.Resource.Id.header_container = global::HopSampleApp.Resource.Id.header_container;
			global::PullToRefresharp.Resource.Id.icon = global::HopSampleApp.Resource.Id.icon;
			global::PullToRefresharp.Resource.Id.pullDownProgressIndicator = global::HopSampleApp.Resource.Id.pullDownProgressIndicator;
			global::PullToRefresharp.Resource.Id.text = global::HopSampleApp.Resource.Id.text;
			global::PullToRefresharp.Resource.Layout.ptrsharp_header = global::HopSampleApp.Resource.Layout.ptrsharp_header;
			global::PullToRefresharp.Resource.String.library_name = global::HopSampleApp.Resource.String.library_name;
			global::PullToRefresharp.Resource.String.ptrsharp_pull_to_refresh = global::HopSampleApp.Resource.String.ptrsharp_pull_to_refresh;
			global::PullToRefresharp.Resource.String.ptrsharp_refreshing = global::HopSampleApp.Resource.String.ptrsharp_refreshing;
			global::PullToRefresharp.Resource.String.ptrsharp_release_to_refresh = global::HopSampleApp.Resource.String.ptrsharp_release_to_refresh;
			global::PullToRefresharp.Resource.Style.HoloProgressMedium = global::HopSampleApp.Resource.Style.HoloProgressMedium;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_contentViewId = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_contentViewId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_fastScrollThumbWidth = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_fastScrollThumbWidth;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerId = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_headerId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerTextColor = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_headerTextColor;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownTension = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_pullDownTension;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullEnabled = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_pullEnabled;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_refreshingText = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_refreshingText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration = global::HopSampleApp.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration;
			global::OpenPeerSdkCSharp.Resource.String.library_name = global::HopSampleApp.Resource.String.library_name;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::HopSampleApp.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::HopSampleApp.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::HopSampleApp.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int SlideInLeft = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SlideInRight = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SlideOutLeft = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int SlideOutRight = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090000
			public const int log_levels_array = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int log_subsystem_array = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int log_subsystem_friend_names_array = 2131296257;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int contentViewId = 2130771969;
			
			// aapt resource value: 0x7f01000c
			public const int fastScrollThumbWidth = 2130771980;
			
			// aapt resource value: 0x7f01000a
			public const int headerIconDrawable = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int headerId = 2130771968;
			
			// aapt resource value: 0x7f010009
			public const int headerTextColor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int ptrHeaderBackground = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int pullDownProgressIndicatorId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int pullDownTension = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int pullEnabled = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int pullToRefreshText = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int refreshingText = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int releaseToRefreshText = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int snapbackDuration = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int ptrsharp_sb_gradient_end = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int ptrsharp_sb_gradient_start = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int ptrsharp_sb_header_text = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ptrsharp_sb_header_text_shadow = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int fastscroll_thumb_width = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int acept = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int avatar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bgcontactlist = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ButtonStyle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cam = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int camera = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cb = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int cb1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ch = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ch3 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int chat = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int chat_alt = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int chat_bubble_left = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int chat_bubble_left_source = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int chat_bubble_right = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int chat_bubble_right_source = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int chatbg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int chattxtedit = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int decline = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int emotion = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int grid = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int imageshape = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int log = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int lokalvideoborder = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int mic = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int mic1 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int MyButtons = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int MyButtons2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int op = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int person = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int progress_medium_holo = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ptrsharp_serious_business_gradient = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int radio = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int radio1 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int record = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int remote = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int robin = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int scam = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int se = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int send = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int serious_business_arrow = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int serious_business_arrow2 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int spiker = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int spinner_20_inner_holo = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int spinner_20_outer_holo = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int videobg = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int wpc = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int wpv = 2130837553;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b001c
			public const int AddButton = 2131427356;
			
			// aapt resource value: 0x7f0b0005
			public const int ButtonCallOnly = 2131427333;
			
			// aapt resource value: 0x7f0b0004
			public const int ButtonCallVideo = 2131427332;
			
			// aapt resource value: 0x7f0b0048
			public const int ButtonMuteMic = 2131427400;
			
			// aapt resource value: 0x7f0b0049
			public const int ButtonStartChat = 2131427401;
			
			// aapt resource value: 0x7f0b0047
			public const int ButtonSwitchCam = 2131427399;
			
			// aapt resource value: 0x7f0b0028
			public const int CallerIDCenter = 2131427368;
			
			// aapt resource value: 0x7f0b0017
			public const int CallerIDTop = 2131427351;
			
			// aapt resource value: 0x7f0b002e
			public const int CallerVideoIDCenter = 2131427374;
			
			// aapt resource value: 0x7f0b0018
			public const int DurationText = 2131427352;
			
			// aapt resource value: 0x7f0b0027
			public const int ImageCallAvatar = 2131427367;
			
			// aapt resource value: 0x7f0b002d
			public const int ImageVideoCallAvatar = 2131427373;
			
			// aapt resource value: 0x7f0b001e
			public const int LinearLayout02 = 2131427358;
			
			// aapt resource value: 0x7f0b0016
			public const int LinearLayout03 = 2131427350;
			
			// aapt resource value: 0x7f0b0003
			public const int Linearcontrols = 2131427331;
			
			// aapt resource value: 0x7f0b0020
			public const int LoggingButton = 2131427360;
			
			// aapt resource value: 0x7f0b001a
			public const int MicButton = 2131427354;
			
			// aapt resource value: 0x7f0b0021
			public const int QRButton2 = 2131427361;
			
			// aapt resource value: 0x7f0b001d
			public const int RecordButton = 2131427357;
			
			// aapt resource value: 0x7f0b0022
			public const int SkipButton1 = 2131427362;
			
			// aapt resource value: 0x7f0b001b
			public const int SpikerButton = 2131427355;
			
			// aapt resource value: 0x7f0b002b
			public const int VideoCallerIDTop = 2131427371;
			
			// aapt resource value: 0x7f0b0008
			public const int avatarImageView = 2131427336;
			
			// aapt resource value: 0x7f0b0014
			public const int badgeAnchorTextView = 2131427348;
			
			// aapt resource value: 0x7f0b0012
			public const int badgeRelativeLayout = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public const int badgeSpacerRelativeLayout = 2131427347;
			
			// aapt resource value: 0x7f0b0029
			public const int btnAnswer = 2131427369;
			
			// aapt resource value: 0x7f0b002f
			public const int btnAnswerVideoCall = 2131427375;
			
			// aapt resource value: 0x7f0b002a
			public const int btnDecline = 2131427370;
			
			// aapt resource value: 0x7f0b0030
			public const int btnDeclineVideoCall = 2131427376;
			
			// aapt resource value: 0x7f0b001f
			public const int btnEndCall = 2131427359;
			
			// aapt resource value: 0x7f0b000a
			public const int bubbleImageView = 2131427338;
			
			// aapt resource value: 0x7f0b0009
			public const int bubbleTextRelativeLayout = 2131427337;
			
			// aapt resource value: 0x7f0b000b
			public const int bubbleTextView = 2131427339;
			
			// aapt resource value: 0x7f0b003b
			public const int buttonZxingFlash = 2131427387;
			
			// aapt resource value: 0x7f0b0026
			public const int callInfo = 2131427366;
			
			// aapt resource value: 0x7f0b0011
			public const int chatIcon = 2131427345;
			
			// aapt resource value: 0x7f0b000c
			public const int contactItemLinearLayout = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int contactItemRelativeLayout = 2131427341;
			
			// aapt resource value: 0x7f0b004a
			public const int contentFrame = 2131427402;
			
			// aapt resource value: 0x7f0b000e
			public const int detailsRelativeLayout = 2131427342;
			
			// aapt resource value: 0x7f0b0002
			public const int editText = 2131427330;
			
			// aapt resource value: 0x7f0b0032
			public const int header = 2131427378;
			
			// aapt resource value: 0x7f0b0031
			public const int header_container = 2131427377;
			
			// aapt resource value: 0x7f0b0034
			public const int icon = 2131427380;
			
			// aapt resource value: 0x7f0b003e
			public const int labelTextView = 2131427390;
			
			// aapt resource value: 0x7f0b0025
			public const int linearLayout = 2131427365;
			
			// aapt resource value: 0x7f0b0036
			public const int linearLayout1 = 2131427382;
			
			// aapt resource value: 0x7f0b0039
			public const int linearLayout2 = 2131427385;
			
			// aapt resource value: 0x7f0b0023
			public const int loginWebView = 2131427363;
			
			// aapt resource value: 0x7f0b004c
			public const int logoutMenuItem = 2131427404;
			
			// aapt resource value: 0x7f0b0046
			public const int myLocalViewLinearLayout = 2131427398;
			
			// aapt resource value: 0x7f0b0045
			public const int myRemoteViewLinearLayout = 2131427397;
			
			// aapt resource value: 0x7f0b0006
			public const int nameTextView = 2131427334;
			
			// aapt resource value: 0x7f0b0044
			public const int progress_bar = 2131427396;
			
			// aapt resource value: 0x7f0b0015
			public const int ptr_wrapper = 2131427349;
			
			// aapt resource value: 0x7f0b0033
			public const int pullDownProgressIndicator = 2131427379;
			
			// aapt resource value: 0x7f0b003d
			public const int relativeLayout = 2131427389;
			
			// aapt resource value: 0x7f0b0001
			public const int sendButton = 2131427329;
			
			// aapt resource value: 0x7f0b0000
			public const int sendRelativeLayout = 2131427328;
			
			// aapt resource value: 0x7f0b004b
			public const int settingsMenuItem = 2131427403;
			
			// aapt resource value: 0x7f0b003c
			public const int settingsSpinnerListItem = 2131427388;
			
			// aapt resource value: 0x7f0b0040
			public const int settingsSwitchListItem = 2131427392;
			
			// aapt resource value: 0x7f0b0042
			public const int settingsTextEditListItem = 2131427394;
			
			// aapt resource value: 0x7f0b0043
			public const int settingsToggleListItem = 2131427395;
			
			// aapt resource value: 0x7f0b0024
			public const int tabHost = 2131427364;
			
			// aapt resource value: 0x7f0b0035
			public const int text = 2131427381;
			
			// aapt resource value: 0x7f0b000f
			public const int textAreaLinearLayout = 2131427343;
			
			// aapt resource value: 0x7f0b0037
			public const int textView1 = 2131427383;
			
			// aapt resource value: 0x7f0b0038
			public const int textView2 = 2131427384;
			
			// aapt resource value: 0x7f0b003a
			public const int textView3 = 2131427386;
			
			// aapt resource value: 0x7f0b0007
			public const int timeTextView = 2131427335;
			
			// aapt resource value: 0x7f0b0041
			public const int toggleButton = 2131427393;
			
			// aapt resource value: 0x7f0b0019
			public const int topLeft = 2131427353;
			
			// aapt resource value: 0x7f0b0010
			public const int usernameTextView = 2131427344;
			
			// aapt resource value: 0x7f0b003f
			public const int valueSpinner = 2131427391;
			
			// aapt resource value: 0x7f0b002c
			public const int videocallInfo = 2131427372;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Chat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChatLeftSideHeaderListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChatLeftSideListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ChatMarginHeaderListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ChatRightSideHeaderListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ChatRightSideListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ContactListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Contacts = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ContactsWithPull = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int EndCall = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Gesture = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Login = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PopupCall = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int PopupVideoCall = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ptrsharp_header = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int QROverlay = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Settings = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int SettingsPullDownViewItem = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SettingsSpinnerListItem = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int SettingsSwitchViewItem = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int SettingsTextEditListItem = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int SettingsTextEditViewItem = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int SettingsToggleListItem = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Splash = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int VideoCall = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int zxingscanneractivitylayout = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int zxingscannerfragmentlayout = 2130903067;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int main_menu = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050009
			public const int ButtonCallOnly = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int ButtonCallVideo = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int CallerIDCenter = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int CallerIDTop = 2131034129;
			
			// aapt resource value: 0x7f05000a
			public const int CallerVideoIDCenter = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int LoggerButton = 2131034130;
			
			// aapt resource value: 0x7f050006
			public const int QRcodeButton = 2131034118;
			
			// aapt resource value: 0x7f050013
			public const int SkipButton = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int VideoCallerIDTop = 2131034119;
			
			// aapt resource value: 0x7f050014
			public const int app_name = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int applicationQRScannerShownAtStart = 2131034133;
			
			// aapt resource value: 0x7f05000d
			public const int btnAnswer = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int btnAnswerVideoCall = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int btnDecline = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int btnDeclineVideoCall = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int btnEndCall = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int hello = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int loading = 2131034117;
			
			// aapt resource value: 0x7f050017
			public const int outgoing_telnet_logger = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int outgoing_telnet_logger_server_prompt = 2131034136;
			
			// aapt resource value: 0x7f050001
			public const int ptrsharp_pull_to_refresh = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ptrsharp_refreshing = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int ptrsharp_release_to_refresh = 2131034114;
			
			// aapt resource value: 0x7f050016
			public const int standard_out_logger = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int telnet_logger = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int telnet_logger_port_prompt = 2131034138;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int HoloProgressMedium = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Theme_Splash = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefresharpWrapper = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public const int PullToRefresharpWrapper_contentViewId = 1;
			
			// aapt resource value: 12
			public const int PullToRefresharpWrapper_fastScrollThumbWidth = 12;
			
			// aapt resource value: 10
			public const int PullToRefresharpWrapper_headerIconDrawable = 10;
			
			// aapt resource value: 0
			public const int PullToRefresharpWrapper_headerId = 0;
			
			// aapt resource value: 9
			public const int PullToRefresharpWrapper_headerTextColor = 9;
			
			// aapt resource value: 8
			public const int PullToRefresharpWrapper_ptrHeaderBackground = 8;
			
			// aapt resource value: 2
			public const int PullToRefresharpWrapper_pullDownProgressIndicatorId = 2;
			
			// aapt resource value: 4
			public const int PullToRefresharpWrapper_pullDownTension = 4;
			
			// aapt resource value: 11
			public const int PullToRefresharpWrapper_pullEnabled = 11;
			
			// aapt resource value: 5
			public const int PullToRefresharpWrapper_pullToRefreshText = 5;
			
			// aapt resource value: 7
			public const int PullToRefresharpWrapper_refreshingText = 7;
			
			// aapt resource value: 6
			public const int PullToRefresharpWrapper_releaseToRefreshText = 6;
			
			// aapt resource value: 3
			public const int PullToRefresharpWrapper_snapbackDuration = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
