/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPPushPresenceRegisterQuery */

#ifndef _Included_com_openpeer_javaapi_OPPushPresenceRegisterQuery
#define _Included_com_openpeer_javaapi_OPPushPresenceRegisterQuery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPPushPresenceRegisterQuery
 * Method:    getID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_openpeer_javaapi_OPPushPresenceRegisterQuery_getID
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushPresenceRegisterQuery
 * Method:    isComplete
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_openpeer_javaapi_OPPushPresenceRegisterQuery_isComplete
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushPresenceRegisterQuery
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushPresenceRegisterQuery_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
