/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPPushMessaging */

#ifndef _Included_com_openpeer_javaapi_OPPushMessaging
#define _Included_com_openpeer_javaapi_OPPushMessaging
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    create
 * Signature: (Lcom/openpeer/javaapi/OPPushMessagingDelegate;Lcom/openpeer/javaapi/OPPushMessagingDatabaseAbstractionDelegate;Lcom/openpeer/javaapi/OPAccount;)Lcom/openpeer/javaapi/OPPushMessaging;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushMessaging_create
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    getID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_openpeer_javaapi_OPPushMessaging_getID
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    getState
 * Signature: (ILjava/lang/String;)Lcom/openpeer/javaapi/PushMessagingStates;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushMessaging_getState
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushMessaging_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    registerDevice
 * Signature: (Lcom/openpeer/javaapi/OPPushMessagingRegisterQueryDelegate;Ljava/lang/String;Landroid/text/format/Time;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/util/List;)Lcom/openpeer/javaapi/OPPushMessagingRegisterQuery;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushMessaging_registerDevice
  (JNIEnv *, jobject, jobject, jstring, jobject, jstring, jboolean, jstring, jstring, jstring, jint, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    push
 * Signature: (Lcom/openpeer/javaapi/OPPushMessagingQueryDelegate;Ljava/util/List;Lcom/openpeer/javaapi/OPPushMessage;)Lcom/openpeer/javaapi/OPPushMessagingQuery;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushMessaging_push
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    recheckNow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushMessaging_recheckNow
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    getMessagesUpdates
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushMessaging_getMessagesUpdates
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    getValues
 * Signature: (Lcom/openpeer/javaapi/OPPushInfo;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushMessaging_getValues
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    createValues
 * Signature: (Ljava/util/Map;)Lcom/openpeer/javaapi/OPElement;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushMessaging_createValues
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    markPushMessageRead
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushMessaging_markPushMessageRead
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    deletePushMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushMessaging_deletePushMessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openpeer_javaapi_OPPushMessaging
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushMessaging_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
