/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPEncryptor */

#ifndef _Included_com_openpeer_javaapi_OPEncryptor
#define _Included_com_openpeer_javaapi_OPEncryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPEncryptor
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/openpeer/javaapi/OPEncryptor;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPEncryptor_create
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_openpeer_javaapi_OPEncryptor
 * Method:    encrypt
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_openpeer_javaapi_OPEncryptor_encrypt
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPEncryptor
 * Method:    coreFinalize
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_openpeer_javaapi_OPEncryptor_coreFinalize
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPEncryptor
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPEncryptor_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
