/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPToken */

#ifndef _Included_com_openpeer_javaapi_OPToken
#define _Included_com_openpeer_javaapi_OPToken
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPToken
 * Method:    hasData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_openpeer_javaapi_OPToken_hasData
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPToken
 * Method:    toDebug
 * Signature: ()Lcom/openpeer/javaapi/OPElement;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPToken_toDebug
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPToken
 * Method:    mergeFrom
 * Signature: (Lcom/openpeer/javaapi/OPToken;Z)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPToken_mergeFrom
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_openpeer_javaapi_OPToken
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Landroid/text/format/Time;)Lcom/openpeer/javaapi/OPToken;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPToken_create__Ljava_lang_String_2Ljava_lang_String_2Landroid_text_format_Time_2
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_openpeer_javaapi_OPToken
 * Method:    create
 * Signature: (Lcom/openpeer/javaapi/OPElement;)Lcom/openpeer/javaapi/OPToken;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPToken_create__Lcom_openpeer_javaapi_OPElement_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_openpeer_javaapi_OPToken
 * Method:    createProof
 * Signature: (Ljava/lang/String;Landroid/text/format/Time;)Lcom/openpeer/javaapi/OPToken;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPToken_createProof
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_openpeer_javaapi_OPToken
 * Method:    createElement
 * Signature: ()Lcom/openpeer/javaapi/OPElement;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPToken_createElement
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPToken
 * Method:    validate
 * Signature: (Lcom/openpeer/javaapi/OPToken;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_openpeer_javaapi_OPToken_validate__Lcom_openpeer_javaapi_OPToken_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_openpeer_javaapi_OPToken
 * Method:    validate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_openpeer_javaapi_OPToken_validate__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_openpeer_javaapi_OPToken
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPToken_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
