/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPConversationThreadComposingStatus */

#ifndef _Included_com_openpeer_javaapi_OPConversationThreadComposingStatus
#define _Included_com_openpeer_javaapi_OPConversationThreadComposingStatus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPConversationThreadComposingStatus
 * Method:    toString
 * Signature: (Lcom/openpeer/javaapi/ComposingStates;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_openpeer_javaapi_OPConversationThreadComposingStatus_toString
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_openpeer_javaapi_OPConversationThreadComposingStatus
 * Method:    toComposingState
 * Signature: (Ljava/lang/String;)Lcom/openpeer/javaapi/ComposingStates;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPConversationThreadComposingStatus_toComposingState
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_openpeer_javaapi_OPConversationThreadComposingStatus
 * Method:    updateComposingStatus
 * Signature: (Ljava/lang/String;Lcom/openpeer/javaapi/ComposingStates;)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPConversationThreadComposingStatus_updateComposingStatus
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_openpeer_javaapi_OPConversationThreadComposingStatus
 * Method:    getComposingStatus
 * Signature: (Ljava/lang/String;)Lcom/openpeer/javaapi/ComposingStates;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPConversationThreadComposingStatus_getComposingStatus
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
