/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPPushMessagingQuery */

#ifndef _Included_com_openpeer_javaapi_OPPushMessagingQuery
#define _Included_com_openpeer_javaapi_OPPushMessagingQuery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPPushMessagingQuery
 * Method:    getID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_openpeer_javaapi_OPPushMessagingQuery_getID
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushMessagingQuery
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushMessagingQuery_cancel
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushMessagingQuery
 * Method:    isUploaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_openpeer_javaapi_OPPushMessagingQuery_isUploaded
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushMessagingQuery
 * Method:    getPushMessage
 * Signature: ()Lcom/openpeer/javaapi/OPPushMessage;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushMessagingQuery_getPushMessage
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushMessagingQuery
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushMessagingQuery_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
