/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPPresenceResources */

#ifndef _Included_com_openpeer_javaapi_OPPresenceResources
#define _Included_com_openpeer_javaapi_OPPresenceResources
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPPresenceResources
 * Method:    create
 * Signature: ()Lcom/openpeer/javaapi/OPPresenceResources;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPresenceResources_create
  (JNIEnv *, jclass);

/*
 * Class:     com_openpeer_javaapi_OPPresenceResources
 * Method:    extract
 * Signature: (Lcom/openpeer/javaapi/OPElement;)Lcom/openpeer/javaapi/OPPresenceResources;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPresenceResources_extract
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPresenceResources
 * Method:    insert
 * Signature: (Lcom/openpeer/javaapi/OPElement;)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPresenceResources_insert
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPresenceResources
 * Method:    hasData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_openpeer_javaapi_OPPresenceResources_hasData
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPresenceResources
 * Method:    toDebug
 * Signature: ()Lcom/openpeer/javaapi/OPElement;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPresenceResources_toDebug
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPresenceResources
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPresenceResources_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
