/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPPushPresence */

#ifndef _Included_com_openpeer_javaapi_OPPushPresence
#define _Included_com_openpeer_javaapi_OPPushPresence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPPushPresence
 * Method:    create
 * Signature: (Lcom/openpeer/javaapi/OPPushPresenceDelegate;Lcom/openpeer/javaapi/OPPushPresenceDatabaseAbstractionDelegate;Lcom/openpeer/javaapi/OPAccount;)Lcom/openpeer/javaapi/OPPushPresence;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushPresence_create
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushPresence
 * Method:    getID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_openpeer_javaapi_OPPushPresence_getID
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushPresence
 * Method:    getState
 * Signature: (ILjava/lang/String;)Lcom/openpeer/javaapi/PushPresenceStates;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushPresence_getState
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_openpeer_javaapi_OPPushPresence
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushPresence_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushPresence
 * Method:    registerDevice
 * Signature: (Lcom/openpeer/javaapi/OPPushPresenceRegisterQueryDelegate;Ljava/lang/String;Landroid/text/format/Time;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/util/List;)Lcom/openpeer/javaapi/OPPushPresenceRegisterQuery;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushPresence_registerDevice
  (JNIEnv *, jobject, jobject, jstring, jobject, jstring, jboolean, jstring, jstring, jstring, jint, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushPresence
 * Method:    send
 * Signature: (Ljava/util/List;Lcom/openpeer/javaapi/OPPushPresenceStatus;)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushPresence_send
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushPresence
 * Method:    recheckNow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushPresence_recheckNow
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushPresence
 * Method:    getValues
 * Signature: (Lcom/openpeer/javaapi/OPPushPresencePushInfo;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushPresence_getValues
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushPresence
 * Method:    createValues
 * Signature: (Ljava/util/Map;)Lcom/openpeer/javaapi/OPElement;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushPresence_createValues
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushPresence
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushPresence_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
