/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPPushPresenceStatus */

#ifndef _Included_com_openpeer_javaapi_OPPushPresenceStatus
#define _Included_com_openpeer_javaapi_OPPushPresenceStatus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPPushPresenceStatus
 * Method:    createEmptyPresence
 * Signature: ()Lcom/openpeer/javaapi/OPElement;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushPresenceStatus_createEmptyPresence
  (JNIEnv *, jclass);

/*
 * Class:     com_openpeer_javaapi_OPPushPresenceStatus
 * Method:    hasData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_openpeer_javaapi_OPPushPresenceStatus_hasData
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushPresenceStatus
 * Method:    toDebug
 * Signature: ()Lcom/openpeer/javaapi/OPElement;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPushPresenceStatus_toDebug
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPushPresenceStatus
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPushPresenceStatus_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
