/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPBackgroundingNotifier */

#ifndef _Included_com_openpeer_javaapi_OPBackgroundingNotifier
#define _Included_com_openpeer_javaapi_OPBackgroundingNotifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPBackgroundingNotifier
 * Method:    getID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_openpeer_javaapi_OPBackgroundingNotifier_getID
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPBackgroundingNotifier
 * Method:    ready
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPBackgroundingNotifier_ready
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPBackgroundingNotifier
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPBackgroundingNotifier_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
