/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPBackgroundingQuery */

#ifndef _Included_com_openpeer_javaapi_OPBackgroundingQuery
#define _Included_com_openpeer_javaapi_OPBackgroundingQuery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPBackgroundingQuery
 * Method:    getID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_openpeer_javaapi_OPBackgroundingQuery_getID
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPBackgroundingQuery
 * Method:    isReady
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_openpeer_javaapi_OPBackgroundingQuery_isReady
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPBackgroundingQuery
 * Method:    totalBackgroundingSubscribersStillPending
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_openpeer_javaapi_OPBackgroundingQuery_totalBackgroundingSubscribersStillPending
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPBackgroundingQuery
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPBackgroundingQuery_releaseCoreObjects
(JNIEnv *, jobject javaObject);

#ifdef __cplusplus
}
#endif
#endif
