/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPDecryptor */

#ifndef _Included_com_openpeer_javaapi_OPDecryptor
#define _Included_com_openpeer_javaapi_OPDecryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPDecryptor
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/openpeer/javaapi/OPDecryptor;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPDecryptor_create
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_openpeer_javaapi_OPDecryptor
 * Method:    decrypt
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_openpeer_javaapi_OPDecryptor_decrypt
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPDecryptor
 * Method:    coreFinalize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_openpeer_javaapi_OPDecryptor_coreFinalize
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPDecryptor
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPDecryptor_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
