/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPPresenceGeographicLocation */

#ifndef _Included_com_openpeer_javaapi_OPPresenceGeographicLocation
#define _Included_com_openpeer_javaapi_OPPresenceGeographicLocation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPPresenceGeographicLocation
 * Method:    create
 * Signature: ()Lcom/openpeer/javaapi/OPPresenceGeographicLocation;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPresenceGeographicLocation_create
  (JNIEnv *, jclass);

/*
 * Class:     com_openpeer_javaapi_OPPresenceGeographicLocation
 * Method:    extract
 * Signature: (Lcom/openpeer/javaapi/OPElement;)Lcom/openpeer/javaapi/OPPresenceGeographicLocation;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPresenceGeographicLocation_extract
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPresenceGeographicLocation
 * Method:    insert
 * Signature: (Lcom/openpeer/javaapi/OPElement;)V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPresenceGeographicLocation_insert
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPresenceGeographicLocation
 * Method:    hasData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_openpeer_javaapi_OPPresenceGeographicLocation_hasData
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPresenceGeographicLocation
 * Method:    toDebug
 * Signature: ()Lcom/openpeer/javaapi/OPElement;
 */
JNIEXPORT jobject JNICALL Java_com_openpeer_javaapi_OPPresenceGeographicLocation_toDebug
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPPresenceGeographicLocation
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPPresenceGeographicLocation_releaseCoreObjects
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
