/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openpeer_javaapi_OPBackgroundingSubscription */

#ifndef _Included_com_openpeer_javaapi_OPBackgroundingSubscription
#define _Included_com_openpeer_javaapi_OPBackgroundingSubscription
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openpeer_javaapi_OPBackgroundingSubscription
 * Method:    getID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_openpeer_javaapi_OPBackgroundingSubscription_getID
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPBackgroundingSubscription
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPBackgroundingSubscription_cancel
  (JNIEnv *, jobject);

/*
 * Class:     com_openpeer_javaapi_OPBackgroundingSubscription
 * Method:    releaseCoreObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openpeer_javaapi_OPBackgroundingSubscription_releaseCoreObjects
(JNIEnv *, jobject javaObject);

#ifdef __cplusplus
}
#endif
#endif
